/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import bj.impots.dgi.emcf.EmcfInfoDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * InfoResponseDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-06T15:15:09.028+01:00[Europe/Prague]")
public class InfoResponseDto {
  @SerializedName("status")
  private Boolean status = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("ifu")
  private String ifu = null;

  @SerializedName("nim")
  private String nim = null;

  @SerializedName("tokenValid")
  private OffsetDateTime tokenValid = null;

  @SerializedName("serverDateTime")
  private OffsetDateTime serverDateTime = null;

  @SerializedName("emcfList")
  private List<EmcfInfoDto> emcfList = null;

  public InfoResponseDto status(Boolean status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Boolean isStatus() {
    return status;
  }

  public void setStatus(Boolean status) {
    this.status = status;
  }

  public InfoResponseDto version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public InfoResponseDto ifu(String ifu) {
    this.ifu = ifu;
    return this;
  }

   /**
   * Get ifu
   * @return ifu
  **/
  @Schema(description = "")
  public String getIfu() {
    return ifu;
  }

  public void setIfu(String ifu) {
    this.ifu = ifu;
  }

  public InfoResponseDto nim(String nim) {
    this.nim = nim;
    return this;
  }

   /**
   * Get nim
   * @return nim
  **/
  @Schema(description = "")
  public String getNim() {
    return nim;
  }

  public void setNim(String nim) {
    this.nim = nim;
  }

  public InfoResponseDto tokenValid(OffsetDateTime tokenValid) {
    this.tokenValid = tokenValid;
    return this;
  }

   /**
   * Get tokenValid
   * @return tokenValid
  **/
  @Schema(description = "")
  public OffsetDateTime getTokenValid() {
    return tokenValid;
  }

  public void setTokenValid(OffsetDateTime tokenValid) {
    this.tokenValid = tokenValid;
  }

  public InfoResponseDto serverDateTime(OffsetDateTime serverDateTime) {
    this.serverDateTime = serverDateTime;
    return this;
  }

   /**
   * Get serverDateTime
   * @return serverDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getServerDateTime() {
    return serverDateTime;
  }

  public void setServerDateTime(OffsetDateTime serverDateTime) {
    this.serverDateTime = serverDateTime;
  }

  public InfoResponseDto emcfList(List<EmcfInfoDto> emcfList) {
    this.emcfList = emcfList;
    return this;
  }

  public InfoResponseDto addEmcfListItem(EmcfInfoDto emcfListItem) {
    if (this.emcfList == null) {
      this.emcfList = new ArrayList<EmcfInfoDto>();
    }
    this.emcfList.add(emcfListItem);
    return this;
  }

   /**
   * Get emcfList
   * @return emcfList
  **/
  @Schema(description = "")
  public List<EmcfInfoDto> getEmcfList() {
    return emcfList;
  }

  public void setEmcfList(List<EmcfInfoDto> emcfList) {
    this.emcfList = emcfList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoResponseDto infoResponseDto = (InfoResponseDto) o;
    return Objects.equals(this.status, infoResponseDto.status) &&
        Objects.equals(this.version, infoResponseDto.version) &&
        Objects.equals(this.ifu, infoResponseDto.ifu) &&
        Objects.equals(this.nim, infoResponseDto.nim) &&
        Objects.equals(this.tokenValid, infoResponseDto.tokenValid) &&
        Objects.equals(this.serverDateTime, infoResponseDto.serverDateTime) &&
        Objects.equals(this.emcfList, infoResponseDto.emcfList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, version, ifu, nim, tokenValid, serverDateTime, emcfList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoResponseDto {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    ifu: ").append(toIndentedString(ifu)).append("\n");
    sb.append("    nim: ").append(toIndentedString(nim)).append("\n");
    sb.append("    tokenValid: ").append(toIndentedString(tokenValid)).append("\n");
    sb.append("    serverDateTime: ").append(toIndentedString(serverDateTime)).append("\n");
    sb.append("    emcfList: ").append(toIndentedString(emcfList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
