/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets InvoiceTypeEnum
 */
@JsonAdapter(InvoiceTypeEnum.Adapter.class)
public enum InvoiceTypeEnum {
  FV("FV"),
  FA("FA"),
  EV("EV"),
  EA("EA");

  private String value;

  InvoiceTypeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static InvoiceTypeEnum fromValue(String text) {
    for (InvoiceTypeEnum b : InvoiceTypeEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<InvoiceTypeEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final InvoiceTypeEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public InvoiceTypeEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return InvoiceTypeEnum.fromValue(String.valueOf(value));
    }
  }
}
