/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InvoiceResponseDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-06T15:15:09.028+01:00[Europe/Prague]")
public class InvoiceResponseDto {
  @SerializedName("uid")
  private String uid = null;

  @SerializedName("ta")
  private Long ta = null;

  @SerializedName("tb")
  private Long tb = null;

  @SerializedName("tc")
  private Long tc = null;

  @SerializedName("td")
  private Long td = null;

  @SerializedName("taa")
  private Long taa = null;

  @SerializedName("tab")
  private Long tab = null;

  @SerializedName("tac")
  private Long tac = null;

  @SerializedName("tad")
  private Long tad = null;

  @SerializedName("tae")
  private Long tae = null;

  @SerializedName("taf")
  private Long taf = null;

  @SerializedName("hab")
  private Long hab = null;

  @SerializedName("had")
  private Long had = null;

  @SerializedName("vab")
  private Long vab = null;

  @SerializedName("vad")
  private Long vad = null;

  @SerializedName("aib")
  private Long aib = null;

  @SerializedName("ts")
  private Long ts = null;

  @SerializedName("total")
  private Long total = null;

  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("errorDesc")
  private String errorDesc = null;

  public InvoiceResponseDto uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(description = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public InvoiceResponseDto ta(Long ta) {
    this.ta = ta;
    return this;
  }

   /**
   * Get ta
   * @return ta
  **/
  @Schema(description = "")
  public Long getTa() {
    return ta;
  }

  public void setTa(Long ta) {
    this.ta = ta;
  }

  public InvoiceResponseDto tb(Long tb) {
    this.tb = tb;
    return this;
  }

   /**
   * Get tb
   * @return tb
  **/
  @Schema(description = "")
  public Long getTb() {
    return tb;
  }

  public void setTb(Long tb) {
    this.tb = tb;
  }

  public InvoiceResponseDto tc(Long tc) {
    this.tc = tc;
    return this;
  }

   /**
   * Get tc
   * @return tc
  **/
  @Schema(description = "")
  public Long getTc() {
    return tc;
  }

  public void setTc(Long tc) {
    this.tc = tc;
  }

  public InvoiceResponseDto td(Long td) {
    this.td = td;
    return this;
  }

   /**
   * Get td
   * @return td
  **/
  @Schema(description = "")
  public Long getTd() {
    return td;
  }

  public void setTd(Long td) {
    this.td = td;
  }

  public InvoiceResponseDto taa(Long taa) {
    this.taa = taa;
    return this;
  }

   /**
   * Get taa
   * @return taa
  **/
  @Schema(description = "")
  public Long getTaa() {
    return taa;
  }

  public void setTaa(Long taa) {
    this.taa = taa;
  }

  public InvoiceResponseDto tab(Long tab) {
    this.tab = tab;
    return this;
  }

   /**
   * Get tab
   * @return tab
  **/
  @Schema(description = "")
  public Long getTab() {
    return tab;
  }

  public void setTab(Long tab) {
    this.tab = tab;
  }

  public InvoiceResponseDto tac(Long tac) {
    this.tac = tac;
    return this;
  }

   /**
   * Get tac
   * @return tac
  **/
  @Schema(description = "")
  public Long getTac() {
    return tac;
  }

  public void setTac(Long tac) {
    this.tac = tac;
  }

  public InvoiceResponseDto tad(Long tad) {
    this.tad = tad;
    return this;
  }

   /**
   * Get tad
   * @return tad
  **/
  @Schema(description = "")
  public Long getTad() {
    return tad;
  }

  public void setTad(Long tad) {
    this.tad = tad;
  }

  public InvoiceResponseDto tae(Long tae) {
    this.tae = tae;
    return this;
  }

   /**
   * Get tae
   * @return tae
  **/
  @Schema(description = "")
  public Long getTae() {
    return tae;
  }

  public void setTae(Long tae) {
    this.tae = tae;
  }

  public InvoiceResponseDto taf(Long taf) {
    this.taf = taf;
    return this;
  }

   /**
   * Get taf
   * @return taf
  **/
  @Schema(description = "")
  public Long getTaf() {
    return taf;
  }

  public void setTaf(Long taf) {
    this.taf = taf;
  }

  public InvoiceResponseDto hab(Long hab) {
    this.hab = hab;
    return this;
  }

   /**
   * Get hab
   * @return hab
  **/
  @Schema(description = "")
  public Long getHab() {
    return hab;
  }

  public void setHab(Long hab) {
    this.hab = hab;
  }

  public InvoiceResponseDto had(Long had) {
    this.had = had;
    return this;
  }

   /**
   * Get had
   * @return had
  **/
  @Schema(description = "")
  public Long getHad() {
    return had;
  }

  public void setHad(Long had) {
    this.had = had;
  }

  public InvoiceResponseDto vab(Long vab) {
    this.vab = vab;
    return this;
  }

   /**
   * Get vab
   * @return vab
  **/
  @Schema(description = "")
  public Long getVab() {
    return vab;
  }

  public void setVab(Long vab) {
    this.vab = vab;
  }

  public InvoiceResponseDto vad(Long vad) {
    this.vad = vad;
    return this;
  }

   /**
   * Get vad
   * @return vad
  **/
  @Schema(description = "")
  public Long getVad() {
    return vad;
  }

  public void setVad(Long vad) {
    this.vad = vad;
  }

  public InvoiceResponseDto aib(Long aib) {
    this.aib = aib;
    return this;
  }

   /**
   * Get aib
   * @return aib
  **/
  @Schema(description = "")
  public Long getAib() {
    return aib;
  }

  public void setAib(Long aib) {
    this.aib = aib;
  }

  public InvoiceResponseDto ts(Long ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Get ts
   * @return ts
  **/
  @Schema(description = "")
  public Long getTs() {
    return ts;
  }

  public void setTs(Long ts) {
    this.ts = ts;
  }

  public InvoiceResponseDto total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(description = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public InvoiceResponseDto errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(description = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public InvoiceResponseDto errorDesc(String errorDesc) {
    this.errorDesc = errorDesc;
    return this;
  }

   /**
   * Get errorDesc
   * @return errorDesc
  **/
  @Schema(description = "")
  public String getErrorDesc() {
    return errorDesc;
  }

  public void setErrorDesc(String errorDesc) {
    this.errorDesc = errorDesc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceResponseDto invoiceResponseDto = (InvoiceResponseDto) o;
    return Objects.equals(this.uid, invoiceResponseDto.uid) &&
        Objects.equals(this.ta, invoiceResponseDto.ta) &&
        Objects.equals(this.tb, invoiceResponseDto.tb) &&
        Objects.equals(this.tc, invoiceResponseDto.tc) &&
        Objects.equals(this.td, invoiceResponseDto.td) &&
        Objects.equals(this.taa, invoiceResponseDto.taa) &&
        Objects.equals(this.tab, invoiceResponseDto.tab) &&
        Objects.equals(this.tac, invoiceResponseDto.tac) &&
        Objects.equals(this.tad, invoiceResponseDto.tad) &&
        Objects.equals(this.tae, invoiceResponseDto.tae) &&
        Objects.equals(this.taf, invoiceResponseDto.taf) &&
        Objects.equals(this.hab, invoiceResponseDto.hab) &&
        Objects.equals(this.had, invoiceResponseDto.had) &&
        Objects.equals(this.vab, invoiceResponseDto.vab) &&
        Objects.equals(this.vad, invoiceResponseDto.vad) &&
        Objects.equals(this.aib, invoiceResponseDto.aib) &&
        Objects.equals(this.ts, invoiceResponseDto.ts) &&
        Objects.equals(this.total, invoiceResponseDto.total) &&
        Objects.equals(this.errorCode, invoiceResponseDto.errorCode) &&
        Objects.equals(this.errorDesc, invoiceResponseDto.errorDesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, ta, tb, tc, td, taa, tab, tac, tad, tae, taf, hab, had, vab, vad, aib, ts, total, errorCode, errorDesc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceResponseDto {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    ta: ").append(toIndentedString(ta)).append("\n");
    sb.append("    tb: ").append(toIndentedString(tb)).append("\n");
    sb.append("    tc: ").append(toIndentedString(tc)).append("\n");
    sb.append("    td: ").append(toIndentedString(td)).append("\n");
    sb.append("    taa: ").append(toIndentedString(taa)).append("\n");
    sb.append("    tab: ").append(toIndentedString(tab)).append("\n");
    sb.append("    tac: ").append(toIndentedString(tac)).append("\n");
    sb.append("    tad: ").append(toIndentedString(tad)).append("\n");
    sb.append("    tae: ").append(toIndentedString(tae)).append("\n");
    sb.append("    taf: ").append(toIndentedString(taf)).append("\n");
    sb.append("    hab: ").append(toIndentedString(hab)).append("\n");
    sb.append("    had: ").append(toIndentedString(had)).append("\n");
    sb.append("    vab: ").append(toIndentedString(vab)).append("\n");
    sb.append("    vad: ").append(toIndentedString(vad)).append("\n");
    sb.append("    aib: ").append(toIndentedString(aib)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDesc: ").append(toIndentedString(errorDesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
