/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import bj.impots.dgi.emcf.AibGroupTypeEnum;
import bj.impots.dgi.emcf.ClientDto;
import bj.impots.dgi.emcf.InvoiceTypeEnum;
import bj.impots.dgi.emcf.ItemDto;
import bj.impots.dgi.emcf.OperatorDto;
import bj.impots.dgi.emcf.PaymentDto;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InvoiceRequestDataDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-06T15:15:09.028+01:00[Europe/Prague]")
public class InvoiceRequestDataDto {
  @SerializedName("ifu")
  private String ifu = null;

  @SerializedName("aib")
  private AibGroupTypeEnum aib = null;

  @SerializedName("type")
  private InvoiceTypeEnum type = null;

  @SerializedName("items")
  private List<ItemDto> items = null;

  @SerializedName("client")
  private ClientDto client = null;

  @SerializedName("operator")
  private OperatorDto operator = null;

  @SerializedName("payment")
  private List<PaymentDto> payment = null;

  @SerializedName("reference")
  private String reference = null;

  public InvoiceRequestDataDto ifu(String ifu) {
    this.ifu = ifu;
    return this;
  }

   /**
   * Get ifu
   * @return ifu
  **/
  @Schema(description = "")
  public String getIfu() {
    return ifu;
  }

  public void setIfu(String ifu) {
    this.ifu = ifu;
  }

  public InvoiceRequestDataDto aib(AibGroupTypeEnum aib) {
    this.aib = aib;
    return this;
  }

   /**
   * Get aib
   * @return aib
  **/
  @Schema(description = "")
  public AibGroupTypeEnum getAib() {
    return aib;
  }

  public void setAib(AibGroupTypeEnum aib) {
    this.aib = aib;
  }

  public InvoiceRequestDataDto type(InvoiceTypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public InvoiceTypeEnum getType() {
    return type;
  }

  public void setType(InvoiceTypeEnum type) {
    this.type = type;
  }

  public InvoiceRequestDataDto items(List<ItemDto> items) {
    this.items = items;
    return this;
  }

  public InvoiceRequestDataDto addItemsItem(ItemDto itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<ItemDto>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @Schema(description = "")
  public List<ItemDto> getItems() {
    return items;
  }

  public void setItems(List<ItemDto> items) {
    this.items = items;
  }

  public InvoiceRequestDataDto client(ClientDto client) {
    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  @Schema(description = "")
  public ClientDto getClient() {
    return client;
  }

  public void setClient(ClientDto client) {
    this.client = client;
  }

  public InvoiceRequestDataDto operator(OperatorDto operator) {
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @Schema(description = "")
  public OperatorDto getOperator() {
    return operator;
  }

  public void setOperator(OperatorDto operator) {
    this.operator = operator;
  }

  public InvoiceRequestDataDto payment(List<PaymentDto> payment) {
    this.payment = payment;
    return this;
  }

  public InvoiceRequestDataDto addPaymentItem(PaymentDto paymentItem) {
    if (this.payment == null) {
      this.payment = new ArrayList<PaymentDto>();
    }
    this.payment.add(paymentItem);
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @Schema(description = "")
  public List<PaymentDto> getPayment() {
    return payment;
  }

  public void setPayment(List<PaymentDto> payment) {
    this.payment = payment;
  }

  public InvoiceRequestDataDto reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @Schema(description = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceRequestDataDto invoiceRequestDataDto = (InvoiceRequestDataDto) o;
    return Objects.equals(this.ifu, invoiceRequestDataDto.ifu) &&
        Objects.equals(this.aib, invoiceRequestDataDto.aib) &&
        Objects.equals(this.type, invoiceRequestDataDto.type) &&
        Objects.equals(this.items, invoiceRequestDataDto.items) &&
        Objects.equals(this.client, invoiceRequestDataDto.client) &&
        Objects.equals(this.operator, invoiceRequestDataDto.operator) &&
        Objects.equals(this.payment, invoiceRequestDataDto.payment) &&
        Objects.equals(this.reference, invoiceRequestDataDto.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ifu, aib, type, items, client, operator, payment, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceRequestDataDto {\n");
    
    sb.append("    ifu: ").append(toIndentedString(ifu)).append("\n");
    sb.append("    aib: ").append(toIndentedString(aib)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
