/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import bj.impots.dgi.emcf.TaxGroupTypeEnum;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ItemDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-06T15:15:09.028+01:00[Europe/Prague]")
public class ItemDto {
  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("price")
  private Long price = null;

  @SerializedName("quantity")
  private Double quantity = null;

  @SerializedName("taxGroup")
  private TaxGroupTypeEnum taxGroup = null;

  @SerializedName("taxSpecific")
  private Long taxSpecific = null;

  @SerializedName("originalPrice")
  private Double originalPrice = null;

  @SerializedName("priceModification")
  private String priceModification = null;

  public ItemDto code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ItemDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ItemDto price(Long price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public Long getPrice() {
    return price;
  }

  public void setPrice(Long price) {
    this.price = price;
  }

  public ItemDto quantity(Double quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public Double getQuantity() {
    return quantity;
  }

  public void setQuantity(Double quantity) {
    this.quantity = quantity;
  }

  public ItemDto taxGroup(TaxGroupTypeEnum taxGroup) {
    this.taxGroup = taxGroup;
    return this;
  }

   /**
   * Get taxGroup
   * @return taxGroup
  **/
  @Schema(description = "")
  public TaxGroupTypeEnum getTaxGroup() {
    return taxGroup;
  }

  public void setTaxGroup(TaxGroupTypeEnum taxGroup) {
    this.taxGroup = taxGroup;
  }

  public ItemDto taxSpecific(Long taxSpecific) {
    this.taxSpecific = taxSpecific;
    return this;
  }

   /**
   * Get taxSpecific
   * @return taxSpecific
  **/
  @Schema(description = "")
  public Long getTaxSpecific() {
    return taxSpecific;
  }

  public void setTaxSpecific(Long taxSpecific) {
    this.taxSpecific = taxSpecific;
  }

  public ItemDto originalPrice(Double originalPrice) {
    this.originalPrice = originalPrice;
    return this;
  }

   /**
   * Get originalPrice
   * @return originalPrice
  **/
  @Schema(description = "")
  public Double getOriginalPrice() {
    return originalPrice;
  }

  public void setOriginalPrice(Double originalPrice) {
    this.originalPrice = originalPrice;
  }

  public ItemDto priceModification(String priceModification) {
    this.priceModification = priceModification;
    return this;
  }

   /**
   * Get priceModification
   * @return priceModification
  **/
  @Schema(description = "")
  public String getPriceModification() {
    return priceModification;
  }

  public void setPriceModification(String priceModification) {
    this.priceModification = priceModification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemDto itemDto = (ItemDto) o;
    return Objects.equals(this.code, itemDto.code) &&
        Objects.equals(this.name, itemDto.name) &&
        Objects.equals(this.price, itemDto.price) &&
        Objects.equals(this.quantity, itemDto.quantity) &&
        Objects.equals(this.taxGroup, itemDto.taxGroup) &&
        Objects.equals(this.taxSpecific, itemDto.taxSpecific) &&
        Objects.equals(this.originalPrice, itemDto.originalPrice) &&
        Objects.equals(this.priceModification, itemDto.priceModification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, price, quantity, taxGroup, taxSpecific, originalPrice, priceModification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemDto {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    taxGroup: ").append(toIndentedString(taxGroup)).append("\n");
    sb.append("    taxSpecific: ").append(toIndentedString(taxSpecific)).append("\n");
    sb.append("    originalPrice: ").append(toIndentedString(originalPrice)).append("\n");
    sb.append("    priceModification: ").append(toIndentedString(priceModification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
