/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PaymentTypeEnum
 */
@JsonAdapter(PaymentTypeEnum.Adapter.class)
public enum PaymentTypeEnum {
  ESPECES("ESPECES"),
  VIREMENT("VIREMENT"),
  CARTEBANCAIRE("CARTEBANCAIRE"),
  MOBILEMONEY("MOBILEMONEY"),
  CHEQUES("CHEQUES"),
  CREDIT("CREDIT"),
  AUTRE("AUTRE");

  private String value;

  PaymentTypeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentTypeEnum fromValue(String text) {
    for (PaymentTypeEnum b : PaymentTypeEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PaymentTypeEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentTypeEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentTypeEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentTypeEnum.fromValue(String.valueOf(value));
    }
  }
}
