/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SecurityElementsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-06T15:15:09.028+01:00[Europe/Prague]")
public class SecurityElementsDto {
  @SerializedName("dateTime")
  private String dateTime = null;

  @SerializedName("qrCode")
  private String qrCode = null;

  @SerializedName("codeMECeFDGI")
  private String codeMECeFDGI = null;

  @SerializedName("counters")
  private String counters = null;

  @SerializedName("nim")
  private String nim = null;

  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("errorDesc")
  private String errorDesc = null;

  public SecurityElementsDto dateTime(String dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  @Schema(description = "")
  public String getDateTime() {
    return dateTime;
  }

  public void setDateTime(String dateTime) {
    this.dateTime = dateTime;
  }

  public SecurityElementsDto qrCode(String qrCode) {
    this.qrCode = qrCode;
    return this;
  }

   /**
   * Get qrCode
   * @return qrCode
  **/
  @Schema(description = "")
  public String getQrCode() {
    return qrCode;
  }

  public void setQrCode(String qrCode) {
    this.qrCode = qrCode;
  }

  public SecurityElementsDto codeMECeFDGI(String codeMECeFDGI) {
    this.codeMECeFDGI = codeMECeFDGI;
    return this;
  }

   /**
   * Get codeMECeFDGI
   * @return codeMECeFDGI
  **/
  @Schema(description = "")
  public String getCodeMECeFDGI() {
    return codeMECeFDGI;
  }

  public void setCodeMECeFDGI(String codeMECeFDGI) {
    this.codeMECeFDGI = codeMECeFDGI;
  }

  public SecurityElementsDto counters(String counters) {
    this.counters = counters;
    return this;
  }

   /**
   * Get counters
   * @return counters
  **/
  @Schema(description = "")
  public String getCounters() {
    return counters;
  }

  public void setCounters(String counters) {
    this.counters = counters;
  }

  public SecurityElementsDto nim(String nim) {
    this.nim = nim;
    return this;
  }

   /**
   * Get nim
   * @return nim
  **/
  @Schema(description = "")
  public String getNim() {
    return nim;
  }

  public void setNim(String nim) {
    this.nim = nim;
  }

  public SecurityElementsDto errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(description = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public SecurityElementsDto errorDesc(String errorDesc) {
    this.errorDesc = errorDesc;
    return this;
  }

   /**
   * Get errorDesc
   * @return errorDesc
  **/
  @Schema(description = "")
  public String getErrorDesc() {
    return errorDesc;
  }

  public void setErrorDesc(String errorDesc) {
    this.errorDesc = errorDesc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecurityElementsDto securityElementsDto = (SecurityElementsDto) o;
    return Objects.equals(this.dateTime, securityElementsDto.dateTime) &&
        Objects.equals(this.qrCode, securityElementsDto.qrCode) &&
        Objects.equals(this.codeMECeFDGI, securityElementsDto.codeMECeFDGI) &&
        Objects.equals(this.counters, securityElementsDto.counters) &&
        Objects.equals(this.nim, securityElementsDto.nim) &&
        Objects.equals(this.errorCode, securityElementsDto.errorCode) &&
        Objects.equals(this.errorDesc, securityElementsDto.errorDesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateTime, qrCode, codeMECeFDGI, counters, nim, errorCode, errorDesc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecurityElementsDto {\n");
    
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    codeMECeFDGI: ").append(toIndentedString(codeMECeFDGI)).append("\n");
    sb.append("    counters: ").append(toIndentedString(counters)).append("\n");
    sb.append("    nim: ").append(toIndentedString(nim)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDesc: ").append(toIndentedString(errorDesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
