/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets TaxGroupTypeEnum
 */
@JsonAdapter(TaxGroupTypeEnum.Adapter.class)
public enum TaxGroupTypeEnum {
  A("A"),
  B("B"),
  C("C"),
  D("D"),
  E("E"),
  F("F");

  private String value;

  TaxGroupTypeEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TaxGroupTypeEnum fromValue(String text) {
    for (TaxGroupTypeEnum b : TaxGroupTypeEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TaxGroupTypeEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final TaxGroupTypeEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TaxGroupTypeEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TaxGroupTypeEnum.fromValue(String.valueOf(value));
    }
  }
}
