/*
 * e-MCF
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package bj.impots.dgi.emcf;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TaxGroupsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-06T15:15:09.028+01:00[Europe/Prague]")
public class TaxGroupsDto {
  @SerializedName("a")
  private Integer a = null;

  @SerializedName("b")
  private Integer b = null;

  @SerializedName("c")
  private Integer c = null;

  @SerializedName("d")
  private Integer d = null;

  @SerializedName("e")
  private Integer e = null;

  @SerializedName("f")
  private Integer f = null;

  @SerializedName("aibA")
  private Integer aibA = null;

  @SerializedName("aibB")
  private Integer aibB = null;

  public TaxGroupsDto a(Integer a) {
    this.a = a;
    return this;
  }

   /**
   * Get a
   * @return a
  **/
  @Schema(description = "")
  public Integer getA() {
    return a;
  }

  public void setA(Integer a) {
    this.a = a;
  }

  public TaxGroupsDto b(Integer b) {
    this.b = b;
    return this;
  }

   /**
   * Get b
   * @return b
  **/
  @Schema(description = "")
  public Integer getB() {
    return b;
  }

  public void setB(Integer b) {
    this.b = b;
  }

  public TaxGroupsDto c(Integer c) {
    this.c = c;
    return this;
  }

   /**
   * Get c
   * @return c
  **/
  @Schema(description = "")
  public Integer getC() {
    return c;
  }

  public void setC(Integer c) {
    this.c = c;
  }

  public TaxGroupsDto d(Integer d) {
    this.d = d;
    return this;
  }

   /**
   * Get d
   * @return d
  **/
  @Schema(description = "")
  public Integer getD() {
    return d;
  }

  public void setD(Integer d) {
    this.d = d;
  }

  public TaxGroupsDto e(Integer e) {
    this.e = e;
    return this;
  }

   /**
   * Get e
   * @return e
  **/
  @Schema(description = "")
  public Integer getE() {
    return e;
  }

  public void setE(Integer e) {
    this.e = e;
  }

  public TaxGroupsDto f(Integer f) {
    this.f = f;
    return this;
  }

   /**
   * Get f
   * @return f
  **/
  @Schema(description = "")
  public Integer getF() {
    return f;
  }

  public void setF(Integer f) {
    this.f = f;
  }

  public TaxGroupsDto aibA(Integer aibA) {
    this.aibA = aibA;
    return this;
  }

   /**
   * Get aibA
   * @return aibA
  **/
  @Schema(description = "")
  public Integer getAibA() {
    return aibA;
  }

  public void setAibA(Integer aibA) {
    this.aibA = aibA;
  }

  public TaxGroupsDto aibB(Integer aibB) {
    this.aibB = aibB;
    return this;
  }

   /**
   * Get aibB
   * @return aibB
  **/
  @Schema(description = "")
  public Integer getAibB() {
    return aibB;
  }

  public void setAibB(Integer aibB) {
    this.aibB = aibB;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxGroupsDto taxGroupsDto = (TaxGroupsDto) o;
    return Objects.equals(this.a, taxGroupsDto.a) &&
        Objects.equals(this.b, taxGroupsDto.b) &&
        Objects.equals(this.c, taxGroupsDto.c) &&
        Objects.equals(this.d, taxGroupsDto.d) &&
        Objects.equals(this.e, taxGroupsDto.e) &&
        Objects.equals(this.f, taxGroupsDto.f) &&
        Objects.equals(this.aibA, taxGroupsDto.aibA) &&
        Objects.equals(this.aibB, taxGroupsDto.aibB);
  }

  @Override
  public int hashCode() {
    return Objects.hash(a, b, c, d, e, f, aibA, aibB);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxGroupsDto {\n");
    
    sb.append("    a: ").append(toIndentedString(a)).append("\n");
    sb.append("    b: ").append(toIndentedString(b)).append("\n");
    sb.append("    c: ").append(toIndentedString(c)).append("\n");
    sb.append("    d: ").append(toIndentedString(d)).append("\n");
    sb.append("    e: ").append(toIndentedString(e)).append("\n");
    sb.append("    f: ").append(toIndentedString(f)).append("\n");
    sb.append("    aibA: ").append(toIndentedString(aibA)).append("\n");
    sb.append("    aibB: ").append(toIndentedString(aibB)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
